# Jekyll Configuration for Mailist Documentation
title: Dokumentacja Mailist
description: Kompletna dokumentacja techniczna platformy email marketingowej Mailist
baseurl: "/docs"
url: "https://mailist.pl"

# Theme
theme: just-the-docs

# Just the Docs configuration
# Color scheme
color_scheme: mailist

# Logo
logo: "/assets/images/logo.png"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Mermaid diagrams
mermaid:
  version: "9.1.6"

# Heading anchors
heading_anchors: true

# Auxiliary links
aux_links:
  "Mailist":
    - "/"
  "Blog":
    - "/blog"
  "GitHub":
    - "https://github.com/mailist-com"

# Auxiliary links position
aux_links_new_tab: false

# Footer
footer_content: "© 2025 Mailist. Wszelkie prawa zastrzeżone. | <a href=\"/polityka-prywatnosci.html\">Polityka Prywatności</a> | <a href=\"/regulamin.html\">Regulamin</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Wróć na górę"

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%d %b %Y o %H:%M"

# Navigation
nav_sort: case_insensitive

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      nav_exclude: false
  - scope:
      path: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Callouts
callouts_level: quiet
callouts:
  note:
    title: Uwaga
    color: blue
  tip:
    title: Wskazówka
    color: green
  warning:
    title: Ostrzeżenie
    color: yellow
  danger:
    title: Niebezpieczeństwo
    color: red
  info:
    title: Informacja
    color: purple

# Author
author:
  name: Mailist
  email: docs@mailist.pl

# SEO
lang: pl
